seed: 123

data:
    directory: "/home/app/src/data_splitted/train"
    labels: "inferred"
    label_mode: "categorical"
    validation_split: 0.2
    image_size: [224, 224]
    batch_size: 32

model:
    weights: "imagenet"
    input_shape: [224, 224, 3]
    classes: 213
    dropout_rate: 0.2
    data_aug_layer:
        
        random_flip:
           mode: "horizontal"

compile:
    optimizer:
        adam:
            learning_rate: 0.001

    loss: "categorical_crossentropy"
    metrics: ["accuracy"]

fit:
    epochs: 150
    callbacks:
        model_checkpoint:
            filepath: "/home/app/src/experiments/exp4/model.{epoch:02d}-{val_loss:.4f}.h5"
            save_best_only: True           
        tensor_board:
                log_dir: "/home/app/src/experiments/exp4/logs"










